# 7장 - 오류 처리

> 뭔가 잘못되면 바로잡을 책임은 바로 우리 프로그래머에게 있다.
> 

깨끗한 코드와 오류처리는 연관이 있다. 상당수 코드들은 전적으로 오류 처리 코드에 좌우된다. 여기서 좌우된다는 표현은 **코드 기반이 오류만 처리한다는 의미가 아니다.**

여기저기 흩어진 오류 처리 코드 때문에 실제 코드가 하는 일을 파악하기가 거의 불가능하다는 의미다.

<aside>
💡 오류 처리는 중요하지만 이로 인해 프로그램 논리를 이해하기 어려워진다면 깨끗한 코드라 부르기 어렵다.

</aside>

# 오류 코드보다 예외를 사용하라

```java
public class DeviceController {
    ...
    piblic void sendShutDown() {
        DeviceHandle handle = getHandle(DEV1);

        if (handle != DeviceHandle.INVALID) {
            retrieveDeviceRecord(handle);

            if (record.getStatus() != DEVICE_SUSPENDED) {
                pauseDevice(handle);
                clearDeviceWorkQueue(handle);
                closeDevice(handle);
            } else {
                logger.log("Device suspended. Unable to shut down");
            }
        } else {
            logger.log("Invalid handle for: " + DEV1.toString());
        }
    }
    ...
}
```

위와 같은 방법을 사용하면 호출자 코드가 복잡해진다. 함수를 호출한 즉시 오류를 확인해야 하기 때문이다. 

오류가 발생하면 예외를 던지면, 실제 구현 로직이 오류 처리 코드와 섞이지 않게 되어 호출자가 깔끔해진다.

```java
public class DeviceController {
    ...
    public void sendShutDown() {
        try {
            tryToShutDown();
        } catch (DeviceShutDownError e) {
            logger.log(e);
        }
    }
    private void tryToshutDown() throw DeviceShutDownError {
        DeviceHandle hadle = getHandle(DEV1);
        DeviceRecord record = retrieveDeviceRecord(handle);

        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
    }

    private DeviceHandle getHandle(DeviceId id) {
        ...
        throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    }
    ...
}
```

보기도 좋아지고, 코드 품질도 좋아졌다.

→ 뒤섞여있던 디바이스 종료 로직과 오류 처리 로직이 분리되었다.

이를 통해 각 개념을 독립적으로 살펴보고 이해할 수 있다.

# Try-Catch-Finally 문부터 작성하라

예외처리는 로직 내부에 **범위를 정의한다**.

try-catch-finally 문에서 `try` 블록에 들어가는 코드를 실행하면 어느 시점에서든 실행이 중단된 후 `catch` 블록으로 넘어갈 수 있다.

try 블록에서 무슨 일이 생겨도 catch 블록은 프로그램 상태를 일관성 있게 유지해야 한다.

예외가 발생할 코드를 짤 때는 try-catch-finally 문을 만들어놓고 시작하면 try 블록에서 무슨 이링 생기든지 호출자가 기대하는 상태를 정의하기 쉬워진다.

---

```java
// 파일이 없으면 예외를 던지는지 알아보는 단위 테스트
@Test(expcted = StroageException.class)
public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
}
```

단위 테스트에 맞춰 다음 코드를 구현했다.

```java
public List<RecordedGrip> retrieveSection(String sectionName) {
    return new ArrayList<RecordedGrip>();
}
```

코드가 예외를 던지지 않으므로 단위 테스트는 실패한다. 잘못된 파일 접근을 시도하게 구현을 변경하자. 아래 코드는 예외를 던진다.

```java
public List<RecordedGrip> retrieveSevtion(String sectionName) {
    try {
        FileInputStream stream = new FileInputStream(sectionName);
    } catch (Exception e) {
        throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
}
```

코드가 예외를 던지므로 이제는 테스트가 성공한다. 이 시점에서 리팩터링이 가능하다.

catch 블록에서 예외 유형을 좁혀 실제로 `FileInputStream` 생성자가 던지는 `FileNotFoundException`을 잡아낸다.

```java
public List<RecordedGrip> retrieveSevtion(String sectionName) {
    try {
        FileInputStream stream = new FileInputStream(sectionName);
        stream.close();
    } catch (FileNotFoundException e) {
        throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
}
```

try-catch; 구조로 범위를 정의했으므로 TDD를 이용해 필요한 나머지 논리를 추가한다. 나머지 논리는 FileInputStream을 생성하는 코드와 close 호출문 사이에 넣으며 오류나 예외가 전혀 발생하지 않는다고 가정한다.

# 미확인(unchecked) 예외를 사용하라

> 여러 해 동안 자바 프로그래머들은 확인된(checked) 예외의 장단점을 놓고 논쟁을 벌여왔다.
안정적인 소프트웨어를 제작하는 요소로 확인된 예외가 반드시 필요하지 않다는 사실이 분명해졌다.
> 

[Java의 체크 된 예외와 체크되지 않은 예외의 차이점](https://ko.gadget-info.com/difference-between-checked)

- 확인된 예외
    - `RuntimeExeption` 클래스를 제외한 `Exeption` 클래스의 모든 하위 클래스
    - `Error`클래스와 그 하위 클래스
    
    → 컴파일 과정에서 발견되는 예외
    
- 확인되지 않은 예외
    - `RuntimeExeption` 클래스와 해당 하위 클래스
    
    → 프로그램 실행 중 발생하는 예외, 컴파일러가 확인할 수 없는 예외
    

확인된 예외는 OCP(Open Closed Principle) 를 위반한다.

메서드에서 확인된 예외를 던졌는데 catch 블록이 세 단계 위에 있다면 그사이 메서드 모두가 선언부에 해당 예외를 정의해야 한다.

→ 하위 단계에서 코드를 변경하면 상위 단계 메서드 선언부를 전부 고쳐야 한다.

최하위 함수를 변경하여 새로운 오류를 던진다고 가정하고 확인된 오류를 던진다면 함수는 선언부에 throws 절을 추가해야 한다.

1. 병경함 함수를 호출하는 함수 모두가 catch 블록에서 새로운 예외를 처리하거나
2. 선언부에 throw 절을 추가해야 한다.

→ 결과적으로 최하위 단계에서 최상위 단계까지 연쇄적인 수정이 일어난다.

⇒ 다르게 해석하면, throws 경로에 위치하는 모든 ㅎ마수가 최하위 함수에서 던지는 예외를 알아야 하므로 캡슐화가 깨진다.

<aside>
💡 확인된 예외를 이용하여 구현하게 되면 안전한 로직을 만들 수 있지만, 일반적인 애플리케이션은 확인된 예외를 통한 이익보다, 의존성이 더 중요하다.

</aside>

# 예외에 의미를 제공하라

> 예외를 던질 때 전후 상황을 충분히 덧붙히면, 오류가 발생한 원인과 위치를 찾기 쉬워진다.
> 

실패한 코드의 의도를 파악하려면 호출 수택 만으로 부족한 경우가 많아. 오류 메시지에 정보(**실패한 연산 이름과 실패 유형**)를 담아 예외와 함께 던진다.

애플리케이션에서 로깅 기능을 사용한다면 catch 블록에서 오류를 기록하도록 충분한 정보를 넘겨주면 좋다.

# 호출자를 고려해 예외 클래스를 정의하라

오류를 분류하는 방법은 수없이 많다.

- 오류가 발생한 위치
- 오류가 발생한 컴포넌트
- 오류 유형
    - 디바이스 실패
    - 네트워크 실패
    - 프로그래밍 오류

> 어플리케이션 오류를 정의할 때 프로그래머에게 가장 중요한 관심사는 오류를 잡아내는 방법이 되어야 한다.
> 

## 나쁜예

```java
ACMEport port = new ACMEport(12);

try {
    port.open();
} catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
} catch (ATM1212UnlokedException e) {
    reportPortError(e);
    logger.log("Unlock exception". e);
} catch (GMXRrror e) {
    reportPortError(e);
    logger.log("Device response exeption");
} finally {
    ...
}
```

위 코드는 중복이 심하다.

대다수 상황에서 오류를 처리하는 방식은 비교적 일정하다.

1. 오류를 기록한다.
2. 프로그램을 계속 수행해도 좋은지 확인한다.

위 경우는 예외에 대앙흐는 방식이 예외 유형과 무관하게 거의 동일하다. 그래서 코드를 간결하게 고치기 쉽다. 

```java
LocalPort port = new LocalPort(12);

try {
    port.open();
} catch (portDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
} finally {
    ...
}
```

호출하는 라이브러리 API를 감싸면서 예외 유형 하나를 반환하게 수정했다.

```java
public class LocalPort {
    private ACMEPort innerPort;

    public LocalPort(int portNumber) {
        innerPort = new ACMEPort(portNumber);
    }

    public void open() {
        try {
            innerPort.open();
        } catch (DeviceResponseException e) {
            throw new PortDeviceFailure(e);
        } catch (ATM1212UnlockedException e) {
            throw new PortDeviceFailure(e);
        } catch (GMXError e) {
            throw new PortDeviceFailure(e);
        }
    }
    ...
}
```

여기서 `LocalPort`클래스는 단순히 `ACMEport`클래스가 던지는 예외를 잡아 변환하는 wrapper 클래스 일뿐이다.

하지만 이러한 wrapper 클래스는 매우 유용하다. 실제로 외부 API를 사용할 때는 감싸기 기법이 최선이다.

- 외부 API를 감싸면 외부 라이브러리와 프로그램 사이에서 의존성이 크게 줄어든다. 나중에 다른 라이브러리로 갈아타도 비용이 적다.
- 감싸기 클래스에서 외부 API를 호출하는 대신 테스트 코드를 넣어주는 방법으로 프로그램을 테스트하기도 쉬워진다.
- 특정 업체가 API를 설계한 방식에 발목 잡히지 않는다. 프로글매이 사용하기 편한 API를 정의하면 그만이다.

port 디바이스 실패를 표현하는 예외유형 하나를 정의했더니 프로그램이 훨씬 깨끗해졌다.

예외 클래스가 하나만 있어도 충분한 코드가 많다.

→ 예외 클래스에 포함된 정보로 오류를 구분해도 괜찮은 경우.

한 예외는 잡아내고 다른 예외는 무시해도 괜찮은 경우라면 여러 예외 클래스를 사용한다.

# 정상 흐름을 정의하라

> 정상 흐름을 정확히 정의하지 않으면 딴길로 샌다.
> 

```java
try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
} catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
}
```

위에서 식비를 비용으로 청구했다면 직원이 청구한 식비를 총계에 더한다. 식비를 비용으로 청구하지 않았다면 일일 기본 식비를 총계에 더한다. 그런데 예외가 논리를 따라가기 어렵게 만든다. 특수 상황을 처리할 필요가 없다면 더 좋지 않을까?

```java
MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
m_total += expenses.getTotal();
```

`ExpensesReportDAO`를 고쳐 청구한 식비가 없다면, 일일 기본 식비를 반환하는 `MealExpense`객체를 반환한다.

```java
public class PerDiemMealExpenses implements MealExpenses {
    public in getTotal() {
        // 기본값으로 일일 기본 식비를 반환
    }
}
```

이러한 형태를 **특수 사례 패턴(Special Case Pattern)**이라 부른다. 클래스를 만들거나 객체를 조작해 특수 사례를 처리하는 방식이다.

클라이언트 코드가 예외적인 상황을 처리할 필요가 없어진다.

# null을 반환하지 마라

> null 반환은 흔히 사용되어 오류를 유발하는 경우가 많다.
> 

```java
public void registerItem(Item item) {
    if (item != null) {
        ItemRegistry registry = peristentStore.getItemRegistry();

        if (registry != null {
            Item existing = registry.getItem(item.getID());

            if (existing.getBillingPeriod().hasRetailOwner()) {
                existing.register(item);
            }
        }
    }
}
```

null을 반환하기 때문에 정상적인 동작 처리를 위해 null 인지 아닌지 확인하는 로직이 필요하여 일거리를 늘린다.

이러한 코드는 호출자가 null 처리를 잊을 경우 문제가 발생하게는 구조로,  문제를 호출자에게 떠넘기기 때문에  좋은 구조라고 볼 수 없다.

이러한 경우 특수 사례가 좋은 해결책이 될 수 있다.

```java
List<Empoloyee> employees = getEmpoloyees();

if (employees != null {
    for(Employee e : employees) {
        totalPay += e.getPay();
    }
}
```

위 `getEmployees`는  null도 반호나한다. 하지만 이런 경우 null반환하는 것이 아니라 빈 리스트를 반환한다면 코드가 훨씬 깔끔해진다.

```java
List<Employee> employees = getEmployees();

for ( Employees e L employees) {
   totalPay += e.getPay();
}
```

자바에는 `Collections.emptyList()`가 있어 미리 정의된 읽기 전용 리스트를 반환한다.

```java
public List<Employee> getEmployees() {
    if ( ... 직원이 없다면 ..) {
        return Collections.emptyList();
    }
}
```

위와 같이 코드를 변경하면 코드도 깔끔해지고 `NullPointerException`이 발생할 가능성도 줄어든다.

# null을 전달하지 마라

> 메서드에서 null을 반환하는 방식도 나쁘지만 메서드로 null을 전달하는 방식은 더 나쁘다.
> 

```java
public class MetricsCalculator {
    public double xProjection(Point p1, Point p2) {
        return (p2.x - p1.x) * 1.5;
    }
    ...
}
```

누군가 인수로 null을 전달하면 NullPointerException이 발생한다.

```java
public class MetricsCalculator {
    public double xProjection(Point p1, Point p2) {
        if (p1 == null || p2 === null) {
            throw InvalidArgumentException(
                "Invalid argument for MetricsCalculator.xProjection");
        }
        return (p2.x - p1.x) * 1.5;
    }
}
```

위 코드로 입력이 null일 경우를 예방 했지만, InvalidaRGUMENTeXCEPTION을 잡아내는 처리기를 추가해야 한다.

```java
public class MetricsCalculator {
    public double xProjection(Point p1, Point p2) {
        assert p1 != null : "p1 should not be null";
        assert p2 != null : "pw should not be null";
        return (p2.x - p1.x) * 1.5;
    }
}
```

위 코드는 assert문을 사용하여 처리했다.

[Java의 assert 키워드](https://www.delftstack.com/ko/howto/java/java-assert/)

문서화가 잘 되어 코드 읽기는 편하지만 문제를 해결하지는 못한다. 누군가 null을 전달하면 여전히 실행 오류가 발생한다.

> 대다수 프로그래밍 언어는 호출자가 실수로 넘기는 null을 적절히 처리하는 방법이 없다.
> 

<aside>
💡 그렇다면 애초에 null을 넘기지 못하도록 금지하는 정책이 합리적이다.

</aside>

즉 인수로 null이 넘어오면 코드에 문제가 있다는 말이다.

→ null을 반환하는 로직을 구현했으므로 null이 넘어오는 것 자체가 문제가 있다는 뜻

# 결론

깨끗한 코드는 읽기도 좋아야 하지만 안정성도 높아야 한다.

- 이 둘은 상충하는 목표가 아님
- 오류 처리를 프로그램 논리와 분리해 별도의 사안으로 고려해야함
    - 더욱 튼튼하고 깨끗한 코드를 작성할 수 있게됨
    - 독립적인 추론이 가능해지며 코드 유지보수성도 크게 높아짐

1. 프로그램 논리와 분리해 별도로 고민하라.
2. 오류 처리를 만들기 전에 흐름을 정확히 파악하면 안 쓸수도 있다.
    - 정상 흐름을 정의하라.
    - 특수 상황 패턴등을 이용
3. null은 사용자의 실수를 유발하므로 되도록 자제해야 한다.